SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;d94b91

-- SQRIBE/TABLE;d94b91
-- Adding 1 row to dbo.OrderItem

SET IDENTITY_INSERT [dbo].[OrderItem] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;d94b91
INSERT INTO [dbo].[OrderItem] ([Id],[OrderId],[Amount],[TotalPrice],[ProductTypeID]) VALUES (1,5,1,2.400000000000000e+001,345);

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[OrderItem] OFF

