SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;0a120d

-- SQRIBE/TABLE;0a120d
-- Adding 3 rows to dbo.Branch

SET IDENTITY_INSERT [dbo].[Branch] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;0a120d
INSERT INTO [dbo].[Branch] ([Id],[AddressId],[Name]) VALUES (2,7,N'Dizengoff Center');
-- SQRIBE/INSERT;0a120d
INSERT INTO [dbo].[Branch] ([Id],[AddressId],[Name]) VALUES (3,8,N'TLV Fashion Mall');
-- SQRIBE/INSERT;0a120d
INSERT INTO [dbo].[Branch] ([Id],[AddressId],[Name]) VALUES (4,9,N'Malcha Mall');

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[Branch] OFF

