SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/TABLE;c2f4f5
-- Adding 3 rows to dbo.AddressUser

BEGIN TRANSACTION

-- SQRIBE/INSERT;c2f4f5
INSERT INTO [dbo].[AddressUser] ([AddressesId],[UsersId]) VALUES (1,5);
-- SQRIBE/INSERT;c2f4f5
INSERT INTO [dbo].[AddressUser] ([AddressesId],[UsersId]) VALUES (3,5);
-- SQRIBE/INSERT;c2f4f5
INSERT INTO [dbo].[AddressUser] ([AddressesId],[UsersId]) VALUES (4,5);

COMMIT TRANSACTION

