SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;d94b91

-- SQRIBE/TABLE;d94b91
-- Adding 1 row to dbo.Address

SET IDENTITY_INSERT [dbo].[Address] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;d94b91
INSERT INTO [dbo].[Address] ([Id],[City],[Street],[BuildingNumber],[Latitude],[Longitude]) VALUES (1,N'Tel Aviv',N'Disingof',263,0.000000000000000e+000,0.000000000000000e+000);

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[Address] OFF

