SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET DATEFORMAT YMD
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/TABLE;c2f4f5
-- Adding 1 row to dbo.Branch

SET IDENTITY_INSERT [dbo].[Branch] ON

BEGIN TRANSACTION

-- SQRIBE/INSERT;c2f4f5
INSERT INTO [dbo].[Branch] ([Id],[AddressId],[Name]) VALUES (1,2,N'Dizengoff Center');

COMMIT TRANSACTION

SET IDENTITY_INSERT [dbo].[Branch] OFF

