SET NUMERIC_ROUNDABORT OFF
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
SET XACT_ABORT ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[Branch] ADD CONSTRAINT [df_Branch_Name] DEFAULT (N'') FOR [Name]
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[OpeningHour] ADD CONSTRAINT [df_OpeningHour_BranchId] DEFAULT ((0)) FOR [BranchId]
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[OpeningHour] ADD CONSTRAINT [df_OpeningHour_DayOfWeek] DEFAULT ((0)) FOR [DayOfWeek]
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[Order] ADD CONSTRAINT [df_Order_UserId] DEFAULT ((0)) FOR [UserId]
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[Order] ADD CONSTRAINT [df_Order_IsCart] DEFAULT (CONVERT([bit],(0))) FOR [IsCart]
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[Order] ADD CONSTRAINT [df_Order_Delivery] DEFAULT ((0)) FOR [Delivery]
GO -- SQRIBE/GO;c2f4f5

-- SQRIBE/OBJ;c2f4f5
ALTER TABLE [dbo].[ProductType] ADD CONSTRAINT [df_ProductType_ColorId] DEFAULT ((0)) FOR [ColorId]
GO -- SQRIBE/GO;c2f4f5
